[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "https://waves.mubi.tech/:splat"
  status = 301
  force = true
  conditions = { Host = "penguinwaves.netlify.app" }